# Basic image setup
# FROM ubuntu:latest
FROM --platform=linux/amd64 ubuntu:latest

RUN apt-get update && apt-get install -y wget
RUN apt-get update && apt-get install vim -y

# Install Miniconda
# RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# Recommend: do that after getting into the container
